<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Str;

class MedicalProductsSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ──────── Medicines ─────────────────────────────────────────
            [
                'group'              => 'Medicines',
                'brand'              => 'Cipla',
                'item_code'          => 'MED-001',
                'name'               => 'Paracetamol 500mg Tab (10s)',
                'print_name'         => 'Paracetamol 500mg',
                'hsn_sac_code'       => '3004',
                'purchase_price'     => 12.00,
                'sale_price'         => 18.00,
                'mrp'                => 18.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Strip',
                'opening_stock'      => 200,
                'current_stock'      => 200,
                'low_level_limit'    => 30,
                'product_description'=> 'Analgesic & antipyretic. Used for fever and mild pain.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Medicines',
                'brand'              => 'Sun Pharma',
                'item_code'          => 'MED-002',
                'name'               => 'Amoxicillin 500mg Cap (10s)',
                'print_name'         => 'Amoxicillin 500mg',
                'hsn_sac_code'       => '3004',
                'purchase_price'     => 35.00,
                'sale_price'         => 52.00,
                'mrp'                => 55.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Strip',
                'opening_stock'      => 150,
                'current_stock'      => 150,
                'low_level_limit'    => 20,
                'product_description'=> 'Broad-spectrum antibiotic for bacterial infections.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Medicines',
                'brand'              => 'Mankind',
                'item_code'          => 'MED-003',
                'name'               => 'Metformin 500mg Tab (10s)',
                'print_name'         => 'Metformin 500mg',
                'hsn_sac_code'       => '3004',
                'purchase_price'     => 22.00,
                'sale_price'         => 32.00,
                'mrp'                => 35.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Strip',
                'opening_stock'      => 300,
                'current_stock'      => 300,
                'low_level_limit'    => 50,
                'product_description'=> 'Oral antidiabetic for Type 2 Diabetes Mellitus.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Medicines',
                'brand'              => 'Cipla',
                'item_code'          => 'MED-004',
                'name'               => 'Atorvastatin 10mg Tab (10s)',
                'print_name'         => 'Atorvastatin 10mg',
                'hsn_sac_code'       => '3004',
                'purchase_price'     => 28.00,
                'sale_price'         => 42.00,
                'mrp'                => 45.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Strip',
                'opening_stock'      => 180,
                'current_stock'      => 180,
                'low_level_limit'    => 25,
                'product_description'=> 'Statin for lowering LDL cholesterol.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Medicines',
                'brand'              => 'Abbott',
                'item_code'          => 'MED-005',
                'name'               => 'Pantoprazole 40mg Tab (10s)',
                'print_name'         => 'Pantoprazole 40mg',
                'hsn_sac_code'       => '3004',
                'purchase_price'     => 32.00,
                'sale_price'         => 48.00,
                'mrp'                => 52.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Strip',
                'opening_stock'      => 220,
                'current_stock'      => 220,
                'low_level_limit'    => 30,
                'product_description'=> 'Proton pump inhibitor for acid reflux & gastric ulcers.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Medicines',
                'brand'              => 'Dr. Reddy\'s',
                'item_code'          => 'MED-006',
                'name'               => 'Amlodipine 5mg Tab (10s)',
                'print_name'         => 'Amlodipine 5mg',
                'hsn_sac_code'       => '3004',
                'purchase_price'     => 18.00,
                'sale_price'         => 28.00,
                'mrp'                => 30.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Strip',
                'opening_stock'      => 250,
                'current_stock'      => 250,
                'low_level_limit'    => 40,
                'product_description'=> 'Calcium channel blocker for hypertension & angina.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Medicines',
                'brand'              => 'Mankind',
                'item_code'          => 'MED-007',
                'name'               => 'Cetirizine 10mg Tab (10s)',
                'print_name'         => 'Cetirizine 10mg',
                'hsn_sac_code'       => '3004',
                'purchase_price'     => 10.00,
                'sale_price'         => 16.00,
                'mrp'                => 18.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Strip',
                'opening_stock'      => 300,
                'current_stock'      => 300,
                'low_level_limit'    => 50,
                'product_description'=> 'Second-generation antihistamine for allergies & urticaria.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Medicines',
                'brand'              => 'Sun Pharma',
                'item_code'          => 'MED-008',
                'name'               => 'Azithromycin 500mg Tab (3s)',
                'print_name'         => 'Azithromycin 500mg',
                'hsn_sac_code'       => '3004',
                'purchase_price'     => 55.00,
                'sale_price'         => 80.00,
                'mrp'                => 85.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Strip',
                'opening_stock'      => 120,
                'current_stock'      => 120,
                'low_level_limit'    => 20,
                'product_description'=> 'Macrolide antibiotic for respiratory tract infections.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Medicines',
                'brand'              => 'Cipla',
                'item_code'          => 'MED-009',
                'name'               => 'Salbutamol Inhaler 100mcg (200 doses)',
                'print_name'         => 'Salbutamol Inhaler',
                'hsn_sac_code'       => '3004',
                'purchase_price'     => 120.00,
                'sale_price'         => 175.00,
                'mrp'                => 185.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 60,
                'current_stock'      => 60,
                'low_level_limit'    => 10,
                'product_description'=> 'Bronchodilator MDI for acute asthma & COPD.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Medicines',
                'brand'              => 'Pfizer',
                'item_code'          => 'MED-010',
                'name'               => 'Ibuprofen 400mg Tab (10s)',
                'print_name'         => 'Ibuprofen 400mg',
                'hsn_sac_code'       => '3004',
                'purchase_price'     => 14.00,
                'sale_price'         => 22.00,
                'mrp'                => 25.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Strip',
                'opening_stock'      => 280,
                'current_stock'      => 280,
                'low_level_limit'    => 40,
                'product_description'=> 'NSAID for pain, fever and inflammation.',
                'enable_tracking'    => true,
            ],

            // ──────── OTC / General ─────────────────────────────────────
            [
                'group'              => 'OTC / General',
                'brand'              => 'Generic',
                'item_code'          => 'OTC-001',
                'name'               => 'ORS Sachet (Electral 21.8g)',
                'print_name'         => 'ORS Electral',
                'hsn_sac_code'       => '3004',
                'purchase_price'     => 8.00,
                'sale_price'         => 12.00,
                'mrp'                => 14.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 500,
                'current_stock'      => 500,
                'low_level_limit'    => 80,
                'product_description'=> 'Oral rehydration salts for diarrhoea & dehydration.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'OTC / General',
                'brand'              => 'Himalaya',
                'item_code'          => 'OTC-002',
                'name'               => 'Antiseptic Liquid 100ml',
                'print_name'         => 'Antiseptic Liquid',
                'hsn_sac_code'       => '3808',
                'purchase_price'     => 45.00,
                'sale_price'         => 65.00,
                'mrp'                => 70.00,
                'cgst_rate'          => 9.00,
                'sgst_rate'          => 9.00,
                'igst_rate'          => 18.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 100,
                'current_stock'      => 100,
                'low_level_limit'    => 15,
                'product_description'=> 'Topical antiseptic for wound care and disinfection.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'OTC / General',
                'brand'              => 'Dabur',
                'item_code'          => 'OTC-003',
                'name'               => 'Glucose Powder 200g (Orange)',
                'print_name'         => 'Glucose-D 200g',
                'hsn_sac_code'       => '1702',
                'purchase_price'     => 55.00,
                'sale_price'         => 78.00,
                'mrp'                => 82.00,
                'cgst_rate'          => 2.50,
                'sgst_rate'          => 2.50,
                'igst_rate'          => 5.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 120,
                'current_stock'      => 120,
                'low_level_limit'    => 20,
                'product_description'=> 'Instant energy supplement for fatigue recovery.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'OTC / General',
                'brand'              => 'Generic',
                'item_code'          => 'OTC-004',
                'name'               => 'Disposable Face Mask (50 pcs)',
                'print_name'         => 'Surgical Mask 3-Ply',
                'hsn_sac_code'       => '6307',
                'purchase_price'     => 75.00,
                'sale_price'         => 120.00,
                'mrp'                => 130.00,
                'cgst_rate'          => 2.50,
                'sgst_rate'          => 2.50,
                'igst_rate'          => 5.00,
                'unit'               => 'Box',
                'opening_stock'      => 80,
                'current_stock'      => 80,
                'low_level_limit'    => 10,
                'product_description'=> '3-ply disposable surgical face mask, BIS certified.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'OTC / General',
                'brand'              => 'Generic',
                'item_code'          => 'OTC-005',
                'name'               => 'Nitrile Examination Gloves M (100 pcs)',
                'print_name'         => 'Nitrile Gloves M',
                'hsn_sac_code'       => '4015',
                'purchase_price'     => 280.00,
                'sale_price'         => 380.00,
                'mrp'                => 400.00,
                'cgst_rate'          => 9.00,
                'sgst_rate'          => 9.00,
                'igst_rate'          => 18.00,
                'unit'               => 'Box',
                'opening_stock'      => 50,
                'current_stock'      => 50,
                'low_level_limit'    => 8,
                'product_description'=> 'Powder-free nitrile examination gloves, medium size.',
                'enable_tracking'    => true,
            ],

            // ──────── Surgical ──────────────────────────────────────────
            [
                'group'              => 'Surgical',
                'brand'              => 'Generic',
                'item_code'          => 'SUR-001',
                'name'               => 'Disposable Syringe 5ml (100 pcs)',
                'print_name'         => 'Syringe 5ml',
                'hsn_sac_code'       => '9018',
                'purchase_price'     => 140.00,
                'sale_price'         => 200.00,
                'mrp'                => 220.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Box',
                'opening_stock'      => 40,
                'current_stock'      => 40,
                'low_level_limit'    => 5,
                'product_description'=> 'Sterile 5ml disposable syringe with needle 23G.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Surgical',
                'brand'              => 'Generic',
                'item_code'          => 'SUR-002',
                'name'               => 'IV Cannula 22G (50 pcs)',
                'print_name'         => 'IV Cannula 22G',
                'hsn_sac_code'       => '9018',
                'purchase_price'     => 320.00,
                'sale_price'         => 450.00,
                'mrp'                => 480.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Box',
                'opening_stock'      => 30,
                'current_stock'      => 30,
                'low_level_limit'    => 5,
                'product_description'=> 'Sterile IV peripheral cannula 22G with injection port.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Surgical',
                'brand'              => 'Generic',
                'item_code'          => 'SUR-003',
                'name'               => 'Crepe Bandage 10cm (1 pcs)',
                'print_name'         => 'Crepe Bandage 10cm',
                'hsn_sac_code'       => '3005',
                'purchase_price'     => 22.00,
                'sale_price'         => 35.00,
                'mrp'                => 38.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 200,
                'current_stock'      => 200,
                'low_level_limit'    => 30,
                'product_description'=> 'Cotton crepe woven elastic bandage for compression.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Surgical',
                'brand'              => 'Generic',
                'item_code'          => 'SUR-004',
                'name'               => 'Surgical Gloves Sterile 7.5 (1 pair)',
                'print_name'         => 'Surgical Gloves 7.5',
                'hsn_sac_code'       => '4015',
                'purchase_price'     => 35.00,
                'sale_price'         => 55.00,
                'mrp'                => 60.00,
                'cgst_rate'          => 9.00,
                'sgst_rate'          => 9.00,
                'igst_rate'          => 18.00,
                'unit'               => 'Pair',
                'opening_stock'      => 100,
                'current_stock'      => 100,
                'low_level_limit'    => 15,
                'product_description'=> 'Sterile powdered latex surgical gloves, size 7.5.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Surgical',
                'brand'              => 'Generic',
                'item_code'          => 'SUR-005',
                'name'               => 'Gauze Swab Sterile 10x10cm (5 pcs)',
                'print_name'         => 'Gauze Swab 10x10',
                'hsn_sac_code'       => '3005',
                'purchase_price'     => 18.00,
                'sale_price'         => 28.00,
                'mrp'                => 30.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 300,
                'current_stock'      => 300,
                'low_level_limit'    => 50,
                'product_description'=> 'Non-woven sterile gauze swab for wound dressing.',
                'enable_tracking'    => true,
            ],

            // ──────── Nutraceuticals ────────────────────────────────────
            [
                'group'              => 'Nutraceuticals',
                'brand'              => 'Abbott',
                'item_code'          => 'NUT-001',
                'name'               => 'Ensure Powder 400g (Vanilla)',
                'print_name'         => 'Ensure 400g Vanilla',
                'hsn_sac_code'       => '2106',
                'purchase_price'     => 580.00,
                'sale_price'         => 720.00,
                'mrp'                => 780.00,
                'cgst_rate'          => 9.00,
                'sgst_rate'          => 9.00,
                'igst_rate'          => 18.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 40,
                'current_stock'      => 40,
                'low_level_limit'    => 8,
                'product_description'=> 'Complete balanced adult nutrition supplement.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Nutraceuticals',
                'brand'              => 'Generic',
                'item_code'          => 'NUT-002',
                'name'               => 'Vitamin C 500mg Tab (10s)',
                'print_name'         => 'Vitamin C 500mg',
                'hsn_sac_code'       => '2936',
                'purchase_price'     => 20.00,
                'sale_price'         => 32.00,
                'mrp'                => 35.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Strip',
                'opening_stock'      => 200,
                'current_stock'      => 200,
                'low_level_limit'    => 30,
                'product_description'=> 'Ascorbic acid supplement for immune support.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Nutraceuticals',
                'brand'              => 'Sun Pharma',
                'item_code'          => 'NUT-003',
                'name'               => 'Calcium + Vitamin D3 Tab (10s)',
                'print_name'         => 'Calcium D3 Tab',
                'hsn_sac_code'       => '2936',
                'purchase_price'     => 42.00,
                'sale_price'         => 62.00,
                'mrp'                => 68.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Strip',
                'opening_stock'      => 180,
                'current_stock'      => 180,
                'low_level_limit'    => 25,
                'product_description'=> 'Bone health supplement combining calcium and Vitamin D3.',
                'enable_tracking'    => true,
            ],

            // ──────── Ayurvedic ─────────────────────────────────────────
            [
                'group'              => 'Ayurvedic',
                'brand'              => 'Himalaya',
                'item_code'          => 'AYU-001',
                'name'               => 'Himalaya Liv.52 Tab (100s)',
                'print_name'         => 'Liv.52 100 Tabs',
                'hsn_sac_code'       => '3004',
                'purchase_price'     => 145.00,
                'sale_price'         => 195.00,
                'mrp'                => 210.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 80,
                'current_stock'      => 80,
                'low_level_limit'    => 10,
                'product_description'=> 'Hepatoprotective & liver tonic formulation.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Ayurvedic',
                'brand'              => 'Dabur',
                'item_code'          => 'AYU-002',
                'name'               => 'Dabur Chyawanprash 500g',
                'print_name'         => 'Chyawanprash 500g',
                'hsn_sac_code'       => '2106',
                'purchase_price'     => 195.00,
                'sale_price'         => 265.00,
                'mrp'                => 280.00,
                'cgst_rate'          => 2.50,
                'sgst_rate'          => 2.50,
                'igst_rate'          => 5.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 60,
                'current_stock'      => 60,
                'low_level_limit'    => 10,
                'product_description'=> 'Traditional ayurvedic immunity booster jam.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Ayurvedic',
                'brand'              => 'Himalaya',
                'item_code'          => 'AYU-003',
                'name'               => 'Himalaya Triphala Tab (60s)',
                'print_name'         => 'Triphala Tabs 60s',
                'hsn_sac_code'       => '3004',
                'purchase_price'     => 95.00,
                'sale_price'         => 130.00,
                'mrp'                => 140.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 70,
                'current_stock'      => 70,
                'low_level_limit'    => 10,
                'product_description'=> 'Digestive tonic for bowel regularity and detox.',
                'enable_tracking'    => true,
            ],

            // ──────── Diagnostics ───────────────────────────────────────
            [
                'group'              => 'Diagnostics',
                'brand'              => 'Generic',
                'item_code'          => 'DIA-001',
                'name'               => 'Blood Glucose Test Strips (50s)',
                'print_name'         => 'Glucose Strips 50s',
                'hsn_sac_code'       => '3822',
                'purchase_price'     => 380.00,
                'sale_price'         => 520.00,
                'mrp'                => 560.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Box',
                'opening_stock'      => 40,
                'current_stock'      => 40,
                'low_level_limit'    => 6,
                'product_description'=> 'Test strips compatible with standard glucometer devices.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Diagnostics',
                'brand'              => 'Generic',
                'item_code'          => 'DIA-002',
                'name'               => 'Pregnancy Test Kit (1s)',
                'print_name'         => 'Pregnancy Test Kit',
                'hsn_sac_code'       => '3822',
                'purchase_price'     => 28.00,
                'sale_price'         => 45.00,
                'mrp'                => 50.00,
                'cgst_rate'          => 6.00,
                'sgst_rate'          => 6.00,
                'igst_rate'          => 12.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 100,
                'current_stock'      => 100,
                'low_level_limit'    => 15,
                'product_description'=> 'Urine-based rapid pregnancy test, >99% accuracy.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Diagnostics',
                'brand'              => 'Generic',
                'item_code'          => 'DIA-003',
                'name'               => 'Digital Thermometer',
                'print_name'         => 'Digital Thermometer',
                'hsn_sac_code'       => '9025',
                'purchase_price'     => 85.00,
                'sale_price'         => 130.00,
                'mrp'                => 145.00,
                'cgst_rate'          => 9.00,
                'sgst_rate'          => 9.00,
                'igst_rate'          => 18.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 50,
                'current_stock'      => 50,
                'low_level_limit'    => 8,
                'product_description'=> 'Fast-read digital clinical thermometer, oral/axillary.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Diagnostics',
                'brand'              => 'Generic',
                'item_code'          => 'DIA-004',
                'name'               => 'Pulse Oximeter (Fingertip)',
                'print_name'         => 'Pulse Oximeter',
                'hsn_sac_code'       => '9018',
                'purchase_price'     => 650.00,
                'sale_price'         => 950.00,
                'mrp'                => 1050.00,
                'cgst_rate'          => 9.00,
                'sgst_rate'          => 9.00,
                'igst_rate'          => 18.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 25,
                'current_stock'      => 25,
                'low_level_limit'    => 4,
                'product_description'=> 'Fingertip pulse oximeter for SpO2 and heart rate measurement.',
                'enable_tracking'    => true,
            ],

            // ──────── Medical Devices ────────────────────────────────────
            [
                'group'              => 'Medical Devices',
                'brand'              => 'Generic',
                'item_code'          => 'DEV-001',
                'name'               => 'Aneroid BP Apparatus',
                'print_name'         => 'BP Apparatus Aneroid',
                'hsn_sac_code'       => '9018',
                'purchase_price'     => 1100.00,
                'sale_price'         => 1500.00,
                'mrp'                => 1650.00,
                'cgst_rate'          => 9.00,
                'sgst_rate'          => 9.00,
                'igst_rate'          => 18.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 15,
                'current_stock'      => 15,
                'low_level_limit'    => 3,
                'product_description'=> 'Aneroid sphygmomanometer with adult cuff, dual tube.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Medical Devices',
                'brand'              => 'Generic',
                'item_code'          => 'DEV-002',
                'name'               => 'Stethoscope (Dual Head)',
                'print_name'         => 'Stethoscope Dual Head',
                'hsn_sac_code'       => '9018',
                'purchase_price'     => 420.00,
                'sale_price'         => 650.00,
                'mrp'                => 720.00,
                'cgst_rate'          => 9.00,
                'sgst_rate'          => 9.00,
                'igst_rate'          => 18.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 20,
                'current_stock'      => 20,
                'low_level_limit'    => 3,
                'product_description'=> 'Dual-head stethoscope for cardiac and pulmonary auscultation.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Medical Devices',
                'brand'              => 'Generic',
                'item_code'          => 'DEV-003',
                'name'               => 'Glucometer Device',
                'print_name'         => 'Glucometer',
                'hsn_sac_code'       => '9027',
                'purchase_price'     => 750.00,
                'sale_price'         => 1050.00,
                'mrp'                => 1150.00,
                'cgst_rate'          => 9.00,
                'sgst_rate'          => 9.00,
                'igst_rate'          => 18.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 20,
                'current_stock'      => 20,
                'low_level_limit'    => 3,
                'product_description'=> 'Blood glucose monitoring device with memory function.',
                'enable_tracking'    => true,
            ],
            [
                'group'              => 'Medical Devices',
                'brand'              => 'Generic',
                'item_code'          => 'DEV-004',
                'name'               => 'Nebulizer (Compressor Type)',
                'print_name'         => 'Compressor Nebulizer',
                'hsn_sac_code'       => '9019',
                'purchase_price'     => 1800.00,
                'sale_price'         => 2500.00,
                'mrp'                => 2800.00,
                'cgst_rate'          => 9.00,
                'sgst_rate'          => 9.00,
                'igst_rate'          => 18.00,
                'unit'               => 'Pcs',
                'opening_stock'      => 10,
                'current_stock'      => 10,
                'low_level_limit'    => 2,
                'product_description'=> 'Piston-driven compressor nebulizer for aerosol therapy.',
                'enable_tracking'    => true,
            ],
        ];

        $count = 0;
        foreach ($products as $product) {
            // Avoid duplicate item_code if already seeded
            if (!Product::where('item_code', $product['item_code'])->exists()) {
                Product::create($product);
                $count++;
            }
        }

        $this->command->info("✅ MedicalProductsSeeder: {$count} products inserted.");
    }
}
